# Generated by Django 4.1.7 on 2023-02-20 07:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_employee_barangay_employee_city_employee_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="contactNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="PH"
            ),
        ),
    ]
