# Generated by Django 4.1.7 on 2023-02-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_alter_employee_gender_employeeleave"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeleave",
            name="date_back",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="employeeleave",
            name="date_leave",
            field=models.DateField(),
        ),
    ]
