# Generated by Django 4.1.7 on 2023-02-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_employeeleave_date_back_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeleave",
            name="time_in",
        ),
        migrations.RemoveField(
            model_name="employeeleave",
            name="time_out",
        ),
    ]
