# Generated by Django 4.1.7 on 2023-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_remove_employeeleave_time_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeleave",
            name="date_back",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employeeleave",
            name="date_leave",
            field=models.DateField(),
        ),
    ]
