# Generated by Django 4.1.7 on 2023-02-22 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0012_alter_employeeleave_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeleave",
            name="employee",
            field=models.ForeignKey(
                default="auth.User",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
